# Generated by Django 5.0.6 on 2024-06-14 12:42

import check_arrangement.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Un appartement portant ce nom éxiste déjà.'}, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bedroom', models.IntegerField(default=1, validators=[check_arrangement.models.CustomMinValueValidator(1, 'Au moins 1 chambre ! On dort où sinon ?'), check_arrangement.models.CustomMaxValueValidator(12)])),
                ('bathroom', models.IntegerField(default=1, validators=[check_arrangement.models.CustomMinValueValidator(0), check_arrangement.models.CustomMaxValueValidator(6)])),
                ('kitchen', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': "Nature d'incident",
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': 'Pièce',
            },
        ),
        migrations.CreateModel(
            name='ApartmentIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(default='', max_length=24, verbose_name='pièce')),
                ('incident_type', models.TextField(default='incident', verbose_name="Type d'incident")),
                ('details', models.CharField(default='', max_length=100, verbose_name='details')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_arrangement.apartment')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
    ]
