# Generated by Django 5.0.6 on 2024-05-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_apartment', models.CharField(max_length=32)),
                ('number_bedroom', models.IntegerField(default=1)),
                ('number_bathroom', models.IntegerField(default=0)),
            ],
        ),
    ]
