# Generated by Django 5.0.6 on 2024-06-20 12:12

import check_arrangement.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'Un appartement portant ce nom éxiste déjà.'}, max_length=32, unique=True, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bedroom', models.PositiveSmallIntegerField(default=1, validators=[check_arrangement.models.CustomMinValueValidator(1, 'Au moins 1 chambre ! On dort où sinon ?'), check_arrangement.models.CustomMaxValueValidator(12)], verbose_name='Chambre')),
                ('bathroom', models.PositiveSmallIntegerField(default=1, validators=[check_arrangement.models.CustomMaxValueValidator(6)], verbose_name='Salle de bain')),
                ('kitchen', models.PositiveSmallIntegerField(default=1, verbose_name='Cuisine')),
            ],
            options={
                'verbose_name': 'Appartement',
                'verbose_name_plural': 'Appartements',
            },
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.CreateModel(
            name='Sheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='Nom')),
                ('room', models.CharField(choices=[('KITCHEN', 'Cuisine'), ('BEDROOM', 'Chambre'), ('BATHROOM', 'Salle de bain'), ('COMMON', 'Espaces communs')], default='KITCHEN', max_length=24, verbose_name='Pièce')),
            ],
            options={
                'verbose_name': 'Accessoire',
                'verbose_name_plural': 'Accessoires',
            },
        ),
        migrations.CreateModel(
            name='ApartmentIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=24, verbose_name='pièce')),
                ('incident_type', models.TextField(verbose_name="Type d'incident")),
                ('details', models.TextField(verbose_name='details')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_arrangement.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentSheets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_HANDLED', 'Non traité'), ('NOT_AVAILABLE', 'Non disponible'), ('HANDLED', 'Préparé'), ('DELIVERY', 'Livré')], default='NOT_HANDLED', max_length=24)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_arrangement.apartment')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_arrangement.sheets')),
            ],
            options={
                'verbose_name': 'Accessoire',
                'verbose_name_plural': 'Accessoires',
                'unique_together': {('apartment', 'sheet')},
            },
        ),
    ]
