# Generated by Django 5.0.6 on 2024-06-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsheets',
            name='status',
            field=models.CharField(choices=[('NOT_HANDLED', 'Non traité'), ('NOT_AVAILABLE', 'Indisponible'), ('HANDLED', 'Préparé'), ('DELIVERY', 'Livré')], default='NOT_HANDLED', max_length=24),
        ),
    ]
