# Generated by Django 5.0.6 on 2024-05-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='name_apartment',
            new_name='name',
        ),
    ]
