# Generated by Django 5.0.6 on 2024-05-18 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0002_rename_name_apartment_apartment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
