# Generated by Django 5.0.6 on 2024-06-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0002_apartmentissues_modal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentissues',
            name='modal',
        ),
    ]
