# Generated by Django 5.0.6 on 2024-05-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0003_apartment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'Appartement', 'verbose_name_plural': 'Appartements'},
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='number_bathroom',
            new_name='bathroom',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='number_bedroom',
            new_name='bedroom',
        ),
    ]
