# Generated by Django 5.0.6 on 2024-05-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0004_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=32), max_length=32),
        ),
    ]
