# Generated by Django 5.0.6 on 2024-05-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0006_alter_apartment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='slug',
            field=models.SlugField(blank=True, max_length=32),
        ),
    ]
