# Generated by Django 5.0.6 on 2024-05-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0007_alter_apartment_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='slug',
            new_name='slugee',
        ),
    ]
