# Generated by Django 5.0.6 on 2024-05-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0008_rename_slug_apartment_slugee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='slugee',
            new_name='slug',
        ),
    ]
