# Generated by Django 5.0.6 on 2024-05-19 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0010_alter_apartment_bathroom_alter_apartment_bedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bedroom',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
