# Generated by Django 5.0.6 on 2024-05-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0011_alter_apartment_bedroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_arrangement.apartment')),
            ],
            options={
                'verbose_name': "Problème d'appartement",
                'verbose_name_plural': "Problèmes d'appartement",
            },
        ),
    ]
