# Generated by Django 5.0.6 on 2024-05-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0012_apartmentissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='kitchen',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='ApartmentIssue',
        ),
    ]
