# Generated by Django 5.0.6 on 2024-05-20 16:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0013_apartment_kitchen_delete_apartmentissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bathroom',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.CreateModel(
            name='ApartmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_arrangement.apartment')),
            ],
            options={
                'verbose_name': "Problème d'appartement",
                'verbose_name_plural': "Problèmes d'appartement",
            },
        ),
    ]
