# Generated by Django 5.0.6 on 2024-05-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0014_alter_apartment_bathroom_apartmentissue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApartmentIssue',
        ),
    ]
