# Generated by Django 5.0.6 on 2024-05-20 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0016_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='description')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_arrangement.apartment')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
            },
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
    ]
