# Generated by Django 5.0.6 on 2024-05-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0017_apartmentissues_delete_issues'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),

    ]
