# Generated by Django 5.0.6 on 2024-05-20 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0018_incidenttype_alter_apartment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IncidentType',
        ),
    ]
