# Generated by Django 5.0.6 on 2024-05-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0021_auto_20240520_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttype',
            name='name',
            field=models.CharField(max_length=21, unique=True),
        ),
    ]
