# Generated by Django 5.0.6 on 2024-05-20 22:21

from django.db import migrations


def add_incident_type(apps, schema_editor):

    IncidentType = apps.get_model('check_arrangement', 'IncidentType')
    incident_types = ['Electricité', 'Plomberie', 'Autres']
    for incident in incident_types:
        IncidentType.objects.create(name=incident)


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0022_alter_incidenttype_name'),
    ]

    operations = [
        migrations.RunPython(add_incident_type)
    ]
