# Generated by Django 5.0.6 on 2024-05-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0023_auto_20240520_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentissues',
            name='description',
        ),
        migrations.AddField(
            model_name='apartmentissues',
            name='details',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='details'),
        ),
    ]
