# Generated by Django 5.0.6 on 2024-05-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0024_remove_apartmentissues_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='incident_details',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='apartment',
            name='incident_type',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
