# Generated by Django 5.0.6 on 2024-05-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0025_apartment_incident_details_apartment_incident_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentissues',
            name='incident_type',
            field=models.TextField(default='incident', verbose_name="Type d'incident"),
        ),
    ]
