# Generated by Django 5.0.6 on 2024-05-29 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0026_apartmentissues_incident_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='incident_details',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='incident_type',
        ),
    ]
