# Generated by Django 5.0.6 on 2024-05-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0027_remove_apartment_incident_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentissues',
            name='room',
            field=models.CharField(default='Espaces communs', max_length=24, unique=True, verbose_name='pièce'),
        ),
    ]
