# Generated by Django 5.0.6 on 2024-05-29 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0028_apartmentissues_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentissues',
            name='room',
        ),
    ]
