# Generated by Django 5.0.6 on 2024-05-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0029_remove_apartmentissues_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentissues',
            name='details',
            field=models.CharField(default='', max_length=100, verbose_name='details'),
        ),
    ]
