# Generated by Django 5.0.6 on 2024-05-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0030_alter_apartmentissues_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenttype',
            options={'verbose_name': "Nature d'incident"},
        ),
        migrations.AddField(
            model_name='apartmentissues',
            name='room',
            field=models.CharField(default='espace commun', max_length=24, verbose_name='pièce'),
        ),
    ]
