# Generated by Django 5.0.6 on 2024-06-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0031_alter_incidenttype_options_apartmentissues_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
            ],
            options={
                'verbose_name': 'Pièce',
            },
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='slug',
        ),
        migrations.AlterField(
            model_name='apartmentissues',
            name='room',
            field=models.CharField(default='', max_length=24, verbose_name='pièce'),
        ),
    ]
