# Generated by Django 5.0.6 on 2024-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0032_rooms_remove_apartment_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='name',
            field=models.CharField(max_length=22),
        ),
    ]
