# Generated by Django 5.0.6 on 2024-06-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0033_alter_rooms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttype',
            name='name',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
