# Generated by Django 5.0.6 on 2024-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0034_alter_incidenttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(error_messages={'unique': 'Un appartement avec ce nom éxiste déjà.'}, max_length=32, unique=True),
        ),
    ]
