# Generated by Django 5.0.6 on 2024-06-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0035_alter_apartment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(error_messages={'unique': ''}, max_length=32, unique=True),
        ),
    ]
