# Generated by Django 5.0.6 on 2024-06-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0036_alter_apartment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
