# Generated by Django 5.0.6 on 2024-06-09 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0037_alter_apartment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='bathroom',
            field=models.IntegerField(default=1, error_messages={'invalid': "Renseigne jusqu'à 6 salle de bains."}, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='bedroom',
            field=models.IntegerField(default=1, error_messages={'invalid': 'Renseigne entre 1 et 12 chambres.'}, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(error_messages={'unique': 'Un appartement portant ce nom éxiste déjà.'}, max_length=32, unique=True),
        ),
    ]
