# Generated by Django 5.0.6 on 2024-06-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_arrangement', '0040_alter_apartment_bathroom_alter_apartment_bedroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenttype',
            name='name',
            field=models.CharField(max_length=22),
        ),
    ]
